[2024-10-10 04:34:42,976] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: mssql_dag.print_contract_detail 2024-10-10T04:34:38.858179+00:00 [queued]>
[2024-10-10 04:34:42,983] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: mssql_dag.print_contract_detail 2024-10-10T04:34:38.858179+00:00 [queued]>
[2024-10-10 04:34:42,984] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-10-10 04:34:42,984] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2024-10-10 04:34:42,984] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-10-10 04:34:42,994] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): print_contract_detail> on 2024-10-10T04:34:38.858179+00:00
[2024-10-10 04:34:42,998] {standard_task_runner.py:52} INFO - Started process 31023 to run task
[2024-10-10 04:34:43,001] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'mssql_dag', 'print_contract_detail', '2024-10-10T04:34:38.858179+00:00', '--job-id', '432', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/mssql_dag.py', '--cfg-path', '/tmp/tmp47lyig7b', '--error-file', '/tmp/tmpx0s_elx2']
[2024-10-10 04:34:43,004] {standard_task_runner.py:77} INFO - Job 432: Subtask print_contract_detail
[2024-10-10 04:34:43,034] {logging_mixin.py:104} INFO - Running <TaskInstance: mssql_dag.print_contract_detail 2024-10-10T04:34:38.858179+00:00 [running]> on host da843a407010
[2024-10-10 04:34:43,070] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mssql_dag
AIRFLOW_CTX_TASK_ID=print_contract_detail
AIRFLOW_CTX_EXECUTION_DATE=2024-10-10T04:34:38.858179+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-10T04:34:38.858179+00:00
[2024-10-10 04:34:43,093] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/mssql_dag.py", line 217, in print_detail_df
    globals()[table_map[table_name]] = query_table(table_name=table_name)
  File "/opt/airflow/dags/mssql_dag.py", line 50, in query_table
    raise ValueError(f"Unknown table name: {table_name}")
ValueError: Unknown table name: tmp_contract
[2024-10-10 04:34:43,100] {taskinstance.py:1551} INFO - Marking task as UP_FOR_RETRY. dag_id=mssql_dag, task_id=print_contract_detail, execution_date=20241010T043438, start_date=20241010T043442, end_date=20241010T043443
[2024-10-10 04:34:43,133] {local_task_job.py:149} INFO - Task exited with return code 1
