[2024-10-09 09:33:10,492] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: mssql_dag.print_member_detail 2024-10-09T09:33:07.906646+00:00 [queued]>
[2024-10-09 09:33:10,499] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: mssql_dag.print_member_detail 2024-10-09T09:33:07.906646+00:00 [queued]>
[2024-10-09 09:33:10,500] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 09:33:10,501] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2024-10-09 09:33:10,502] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 09:33:10,511] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): print_member_detail> on 2024-10-09T09:33:07.906646+00:00
[2024-10-09 09:33:10,515] {standard_task_runner.py:52} INFO - Started process 14269 to run task
[2024-10-09 09:33:10,518] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'mssql_dag', 'print_member_detail', '2024-10-09T09:33:07.906646+00:00', '--job-id', '86', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/mssql_dag.py', '--cfg-path', '/tmp/tmp7_usa_ns', '--error-file', '/tmp/tmp0dmirshh']
[2024-10-09 09:33:10,522] {standard_task_runner.py:77} INFO - Job 86: Subtask print_member_detail
[2024-10-09 09:33:10,555] {logging_mixin.py:104} INFO - Running <TaskInstance: mssql_dag.print_member_detail 2024-10-09T09:33:07.906646+00:00 [running]> on host da843a407010
[2024-10-09 09:33:10,609] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mssql_dag
AIRFLOW_CTX_TASK_ID=print_member_detail
AIRFLOW_CTX_EXECUTION_DATE=2024-10-09T09:33:07.906646+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-09T09:33:07.906646+00:00
[2024-10-09 09:33:10,613] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: print_detail_df() missing 1 required positional argument: 'table_name'
[2024-10-09 09:33:10,621] {taskinstance.py:1551} INFO - Marking task as UP_FOR_RETRY. dag_id=mssql_dag, task_id=print_member_detail, execution_date=20241009T093307, start_date=20241009T093310, end_date=20241009T093310
[2024-10-09 09:33:10,692] {local_task_job.py:149} INFO - Task exited with return code 1
