[2024-10-10 02:17:20,484] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: mssql_dag.query_receipt 2024-10-10T02:17:19.039387+00:00 [queued]>
[2024-10-10 02:17:20,491] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: mssql_dag.query_receipt 2024-10-10T02:17:19.039387+00:00 [queued]>
[2024-10-10 02:17:20,492] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-10-10 02:17:20,492] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2024-10-10 02:17:20,492] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-10-10 02:17:20,501] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): query_receipt> on 2024-10-10T02:17:19.039387+00:00
[2024-10-10 02:17:20,505] {standard_task_runner.py:52} INFO - Started process 61763 to run task
[2024-10-10 02:17:20,508] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'mssql_dag', 'query_receipt', '2024-10-10T02:17:19.039387+00:00', '--job-id', '241', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/mssql_dag.py', '--cfg-path', '/tmp/tmp890dufr9', '--error-file', '/tmp/tmpxpx5rdt9']
[2024-10-10 02:17:20,511] {standard_task_runner.py:77} INFO - Job 241: Subtask query_receipt
[2024-10-10 02:17:20,546] {logging_mixin.py:104} INFO - Running <TaskInstance: mssql_dag.query_receipt 2024-10-10T02:17:19.039387+00:00 [running]> on host da843a407010
[2024-10-10 02:17:20,577] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mssql_dag
AIRFLOW_CTX_TASK_ID=query_receipt
AIRFLOW_CTX_EXECUTION_DATE=2024-10-10T02:17:19.039387+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-10T02:17:19.039387+00:00
[2024-10-10 02:17:20,617] {python.py:151} INFO - Done. Returned value was: Empty DataFrame
Columns: [PAY_ID, PAY_MEMB_NO, PAY_TYPE, PAY_DOC_NO, PAY_SAVING_DOC_NO, PAY_DATE, PAY_DUE_DATE, PAY_OP_CODE1, PAY_OP_CODE2, PAY_ACC_NO, PAY_OLD_SHR, PAY_OLD_INT, PAY_SAVE_STS, PAY_BANK_TYPE, PAY_MEMB_DEPT, PAY_USER_ID, PAY_FINE_AMT, PAY_OVER_AMT, PAY_PRINT_DATE, PAY_PRINT_OP_CODE, POST_DATETIME, PAY_ITEM, PAY_PROM_TYPE, PAY_PROM_YY, PAY_PROM_NO, PAY_PROM_BRH, PAY_PERD, PAY_AMT1, PAY_AMT2, PAY_RECV_AMT1, PAY_RECV_AMT2, PAY_MONTH_AMT1, PAY_MONTH_AMT2, PAY_ACC_AMT1, PAY_ACC_AMT2, PAY_RET_AMT2, PAY_OLD_BAL, PAY_ACCU_INT, PAY_PROM_STS, PAY_PROM_INT, PAY_RINT_AMT, PAY_DESC, PAY_REF_NO, PAY_REF_ID, PAY_PERD_AMT, PAY_COND_TYPE]
Index: []
[2024-10-10 02:17:20,619] {xcom.py:229} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2024-10-10 02:17:20,620] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1364, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1943, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/xcom.py", line 79, in set
    value = XCom.serialize_value(value)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/xcom.py", line 226, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'DataFrame' is not JSON serializable
[2024-10-10 02:17:20,622] {taskinstance.py:1551} INFO - Marking task as UP_FOR_RETRY. dag_id=mssql_dag, task_id=query_receipt, execution_date=20241010T021719, start_date=20241010T021720, end_date=20241010T021720
[2024-10-10 02:17:20,640] {local_task_job.py:149} INFO - Task exited with return code 1
