[2024-10-09 16:19:39,933] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: mssql_dag.print_receipt_detail 2024-10-09T16:19:35.085473+00:00 [queued]>
[2024-10-09 16:19:39,941] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: mssql_dag.print_receipt_detail 2024-10-09T16:19:35.085473+00:00 [queued]>
[2024-10-09 16:19:39,941] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 16:19:39,942] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2024-10-09 16:19:39,943] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 16:19:39,954] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): print_receipt_detail> on 2024-10-09T16:19:35.085473+00:00
[2024-10-09 16:19:39,958] {standard_task_runner.py:52} INFO - Started process 19373 to run task
[2024-10-09 16:19:39,961] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'mssql_dag', 'print_receipt_detail', '2024-10-09T16:19:35.085473+00:00', '--job-id', '112', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/mssql_dag.py', '--cfg-path', '/tmp/tmpsux6kn97', '--error-file', '/tmp/tmps841p473']
[2024-10-09 16:19:39,964] {standard_task_runner.py:77} INFO - Job 112: Subtask print_receipt_detail
[2024-10-09 16:19:40,001] {logging_mixin.py:104} INFO - Running <TaskInstance: mssql_dag.print_receipt_detail 2024-10-09T16:19:35.085473+00:00 [running]> on host da843a407010
[2024-10-09 16:19:40,039] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mssql_dag
AIRFLOW_CTX_TASK_ID=print_receipt_detail
AIRFLOW_CTX_EXECUTION_DATE=2024-10-09T16:19:35.085473+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-09T16:19:35.085473+00:00
[2024-10-09 16:19:40,042] {logging_mixin.py:104} INFO - Empty DataFrame
Columns: []
Index: []
[2024-10-09 16:19:40,044] {logging_mixin.py:104} INFO - <class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Empty DataFrameNone
[2024-10-09 16:19:40,045] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/mssql_dag.py", line 124, in print_detail_df
    print(df.describe())
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 9980, in describe
    raise ValueError("Cannot describe a DataFrame without columns")
ValueError: Cannot describe a DataFrame without columns
[2024-10-09 16:19:40,056] {taskinstance.py:1551} INFO - Marking task as UP_FOR_RETRY. dag_id=mssql_dag, task_id=print_receipt_detail, execution_date=20241009T161935, start_date=20241009T161939, end_date=20241009T161940
[2024-10-09 16:19:40,094] {local_task_job.py:149} INFO - Task exited with return code 1
