[2024-10-10 03:29:44,592] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: mssql_dag.query_member 2024-10-10T03:29:43.702036+00:00 [queued]>
[2024-10-10 03:29:44,599] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: mssql_dag.query_member 2024-10-10T03:29:43.702036+00:00 [queued]>
[2024-10-10 03:29:44,599] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-10-10 03:29:44,600] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2024-10-10 03:29:44,601] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-10-10 03:29:44,611] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): query_member> on 2024-10-10T03:29:43.702036+00:00
[2024-10-10 03:29:44,616] {standard_task_runner.py:52} INFO - Started process 99293 to run task
[2024-10-10 03:29:44,619] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'mssql_dag', 'query_member', '2024-10-10T03:29:43.702036+00:00', '--job-id', '302', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/mssql_dag.py', '--cfg-path', '/tmp/tmpexqu028m', '--error-file', '/tmp/tmpiy9op3ml']
[2024-10-10 03:29:44,622] {standard_task_runner.py:77} INFO - Job 302: Subtask query_member
[2024-10-10 03:29:44,655] {logging_mixin.py:104} INFO - Running <TaskInstance: mssql_dag.query_member 2024-10-10T03:29:43.702036+00:00 [running]> on host da843a407010
[2024-10-10 03:29:44,687] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mssql_dag
AIRFLOW_CTX_TASK_ID=query_member
AIRFLOW_CTX_EXECUTION_DATE=2024-10-10T03:29:43.702036+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-10T03:29:43.702036+00:00
[2024-10-10 03:29:44,771] {logging_mixin.py:104} INFO - All records deleted from table 'tmp_member' successfully.
[2024-10-10 03:29:44,800] {logging_mixin.py:104} INFO - Error inserting DataFrame: (207, b"Invalid column name 'MAST_NAME'.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")
[2024-10-10 03:29:44,800] {python.py:151} INFO - Done. Returned value was: None
[2024-10-10 03:29:44,808] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=mssql_dag, task_id=query_member, execution_date=20241010T032943, start_date=20241010T032944, end_date=20241010T032944
[2024-10-10 03:29:44,830] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-10 03:29:44,871] {local_task_job.py:149} INFO - Task exited with return code 0
