[2024-10-09 16:17:26,562] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: mssql_dag.print_member_detail 2024-10-09T16:17:23.919690+00:00 [queued]>
[2024-10-09 16:17:26,570] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: mssql_dag.print_member_detail 2024-10-09T16:17:23.919690+00:00 [queued]>
[2024-10-09 16:17:26,582] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 16:17:26,583] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2024-10-09 16:17:26,584] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 16:17:26,598] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): print_member_detail> on 2024-10-09T16:17:23.919690+00:00
[2024-10-09 16:17:26,611] {standard_task_runner.py:52} INFO - Started process 17999 to run task
[2024-10-09 16:17:26,613] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'mssql_dag', 'print_member_detail', '2024-10-09T16:17:23.919690+00:00', '--job-id', '105', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/mssql_dag.py', '--cfg-path', '/tmp/tmpvvxdljam', '--error-file', '/tmp/tmpht9occkx']
[2024-10-09 16:17:26,617] {standard_task_runner.py:77} INFO - Job 105: Subtask print_member_detail
[2024-10-09 16:17:26,654] {logging_mixin.py:104} INFO - Running <TaskInstance: mssql_dag.print_member_detail 2024-10-09T16:17:23.919690+00:00 [running]> on host da843a407010
[2024-10-09 16:17:26,758] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mssql_dag
AIRFLOW_CTX_TASK_ID=print_member_detail
AIRFLOW_CTX_EXECUTION_DATE=2024-10-09T16:17:23.919690+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-09T16:17:23.919690+00:00
[2024-10-09 16:17:26,760] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: print_detail_df() missing 1 required positional argument: 'table_name'
[2024-10-09 16:17:26,761] {taskinstance.py:1551} INFO - Marking task as UP_FOR_RETRY. dag_id=mssql_dag, task_id=print_member_detail, execution_date=20241009T161723, start_date=20241009T161726, end_date=20241009T161726
[2024-10-09 16:17:26,786] {local_task_job.py:149} INFO - Task exited with return code 1
