[2024-10-09 09:04:18,294] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: mssql_dag.print_receipt_detail 2024-10-09T09:04:14.096741+00:00 [queued]>
[2024-10-09 09:04:18,316] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: mssql_dag.print_receipt_detail 2024-10-09T09:04:14.096741+00:00 [queued]>
[2024-10-09 09:04:18,318] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 09:04:18,319] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2024-10-09 09:04:18,320] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 09:04:18,331] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): print_receipt_detail> on 2024-10-09T09:04:14.096741+00:00
[2024-10-09 09:04:18,337] {standard_task_runner.py:52} INFO - Started process 98645 to run task
[2024-10-09 09:04:18,340] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'mssql_dag', 'print_receipt_detail', '2024-10-09T09:04:14.096741+00:00', '--job-id', '49', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/mssql_dag.py', '--cfg-path', '/tmp/tmpc14sdh7y', '--error-file', '/tmp/tmp4p93qlks']
[2024-10-09 09:04:18,344] {standard_task_runner.py:77} INFO - Job 49: Subtask print_receipt_detail
[2024-10-09 09:04:18,377] {logging_mixin.py:104} INFO - Running <TaskInstance: mssql_dag.print_receipt_detail 2024-10-09T09:04:14.096741+00:00 [running]> on host da843a407010
[2024-10-09 09:04:18,409] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mssql_dag
AIRFLOW_CTX_TASK_ID=print_receipt_detail
AIRFLOW_CTX_EXECUTION_DATE=2024-10-09T09:04:14.096741+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-09T09:04:14.096741+00:00
[2024-10-09 09:04:18,410] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/mssql_dag.py", line 93, in print_detail_df
    if df is not None and not df.empty:
AttributeError: 'str' object has no attribute 'empty'
[2024-10-09 09:04:18,433] {taskinstance.py:1551} INFO - Marking task as UP_FOR_RETRY. dag_id=mssql_dag, task_id=print_receipt_detail, execution_date=20241009T090414, start_date=20241009T090418, end_date=20241009T090418
[2024-10-09 09:04:18,522] {local_task_job.py:149} INFO - Task exited with return code 1
