[2024-10-09 09:11:26,283] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: mssql_dag.print_contract_detail 2024-10-09T09:06:23.422085+00:00 [queued]>
[2024-10-09 09:11:26,289] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: mssql_dag.print_contract_detail 2024-10-09T09:06:23.422085+00:00 [queued]>
[2024-10-09 09:11:26,290] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 09:11:26,290] {taskinstance.py:1088} INFO - Starting attempt 2 of 2
[2024-10-09 09:11:26,291] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 09:11:26,299] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): print_contract_detail> on 2024-10-09T09:06:23.422085+00:00
[2024-10-09 09:11:26,303] {standard_task_runner.py:52} INFO - Started process 2794 to run task
[2024-10-09 09:11:26,306] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'mssql_dag', 'print_contract_detail', '2024-10-09T09:06:23.422085+00:00', '--job-id', '62', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/mssql_dag.py', '--cfg-path', '/tmp/tmph4n496ns', '--error-file', '/tmp/tmprkzb7e2i']
[2024-10-09 09:11:26,309] {standard_task_runner.py:77} INFO - Job 62: Subtask print_contract_detail
[2024-10-09 09:11:26,337] {logging_mixin.py:104} INFO - Running <TaskInstance: mssql_dag.print_contract_detail 2024-10-09T09:06:23.422085+00:00 [running]> on host da843a407010
[2024-10-09 09:11:26,366] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mssql_dag
AIRFLOW_CTX_TASK_ID=print_contract_detail
AIRFLOW_CTX_EXECUTION_DATE=2024-10-09T09:06:23.422085+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-09T09:06:23.422085+00:00
[2024-10-09 09:11:26,367] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: print_detail_df() missing 1 required positional argument: 'table_name'
[2024-10-09 09:11:26,369] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=mssql_dag, task_id=print_contract_detail, execution_date=20241009T090623, start_date=20241009T091126, end_date=20241009T091126
[2024-10-09 09:11:26,398] {local_task_job.py:149} INFO - Task exited with return code 1
